version: 2
jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint
          command: |
            shellcheck -x test/repo-sync.sh
  lint-charts:
    docker:
      - image: gcr.io/kubernetes-charts-ci/test-image:v2.0.2
    steps:
      - checkout
      - run:
          name: lint
          command: |
            git remote add dsys-stable https://github.com/dsys/charts
            git fetch dsys-stable master
            chart_test.sh --config test/.testenv --no-install
  sync:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: sync
          command: test/repo-sync.sh
workflows:
  version: 2
  sync:
    # triggers:
    #   - schedule:
    #       cron: "23,53 * * * *"
    #       filters:
    #         branches:
    #           only:
    #             - master
    jobs:
      - lint-scripts
      - lint-charts
      - sync
          requires:
            - lint-scripts
            - lint-charts
