apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudsql-proxy.fullname" . }}-config
  labels:
    app: {{ template "cloudsql-proxy.name" . }}
    chart: {{ template "cloudsql-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  credentials.json: {{ .Values.settings.iamCredentials | b64enc }}
