apiVersion: v1
kind: Service
metadata:
  name: {{ template "cloudsql-proxy.fullname" . }}
  labels:
    app: {{ template "cloudsql-proxy.name" . }}
    chart: {{ template "cloudsql-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: {{ template "cloudsql-proxy.name" . }}
    release: {{ .Release.Name }}
