apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prisma.fullname" . }}-config
  labels:
    app: {{ template "prisma.name" . }}
    chart: {{ template "prisma.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  PRISMA_CONFIG: {{ .Values.settings.PRISMA_CONFIG | b64enc }}
