apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "multi-api.fullname" . }}-prisma-hook
  labels:
    app: {{ template "multi-api.name" . }}-prisma-hook
    chart: {{ template "multi-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "multi-api.name" . }}-prisma-hook
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PRISMA_ENDPOINT
            value: "{{ .Values.settings.prisma.endpoint }}"
          - name: PRISMA_MANAGEMENT_API_SECRET
            value: "{{ .Values.settings.prisma.managementApiSecret }}"
          command: [ "yarn", "run", "deploy:prisma" ]
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
